services:
  distributor:
    build: 
      context: /self_distributing_system
      dockerfile: dockerfile
    command: -sp "../server;../readn" Distributor.o
    working_dir: /app/distributor
    environment:
      - REMOTE1_IP=remote1
      - REMOTE2_IP=remote2
    networks:
      - my_network
    ports:
      - 3500:3500
      - 8080:8080

  remote1:
    build: 
      context: /self_distributing_system
      dockerfile: dockerfile
    command: -sp ../readn RemoteDist.o
    working_dir: /app/distributor
    networks:
      - my_network
    ports:
      - 8081:8081
      - 2010:2010

  remote2:
    build: 
      context: /self_distributing_system
      dockerfile: dockerfile
    command: -sp ../readn RemoteDist.o 8082 2011
    working_dir: /app/distributor
    networks:
      - my_network
    ports:
      - 8082:8082
      - 2011:2011

networks:
  my_network:
    driver: bridge
