apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      containers:
      - name: distributor-container
        image: heitorhs/selfdistributordana:v1.0
        args: ["-sp", "../server;../readn", "Distributor.o"]
        ports:
        - containerPort: 3500
        - containerPort: 8080
        env:
        - name: REMOTE1_IP
          value: remote1-service
        - name: REMOTE2_IP
          value: remote2-service
        - name: READ_FACTOR
          value: 2

---
apiVersion: v1
kind: Service
metadata:
  name: distributor-service
spec:
  type: NodePort
  selector:
    app: distributor
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
    - protocol: TCP
      port: 8080
      targetPort: 8080
